version: "3.3"

services:
  mysqldb:
    image: mysql:8
    container_name: mysqldbco
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'achatdb'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: '3306:3306'

    volumes:
      - db:/var/lib/mysql

  spring-service:
    image: alakrms/achat
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb/achatdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb