version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: on-failure
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_HOST: '%'
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
  achatback:
    depends_on:
      - mysqldb
    build: ./
    image:  abdessalembench/achat
    restart: on-failure
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
