version: "3.3"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'devops'
      MYSQL_DATABASE: 'achatdb'
      MYSQL_USER: 'devops'
      MYSQL_PASSWORD: 'devops'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
  achatback:
    depends_on:
      - mysqldb
    image:  abdessalembench/achat
    restart: on-failure
    ports:
      - 8089:8089
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
