version: "3"


services:
  backapp:
    image: alakrms/achat:latest
    ports:
      - "8089:8089"
    environment:
      driverClassName: com.mysql.jdbc.Driver
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/achatdb?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      MYSQL_PORT: 3306
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - /db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=root