version: "3"


services:
  backapp:
    image: alakrms/achat:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.1.126:3306/achatdb?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "devops"
      SPRING_DATASOURCE_PASSWORD: "devops"
      MYSQL_PORT: 3307
    restart: always
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - /db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=devops
      - MYSQL_DATABASE=devops